# -*- coding: utf-8 -*-
"""8_While_Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1facprc0ub2NBj70Bk9n2m4bOPppzRmCF

##Lets start this session with an exercise
"""

#print all characters your first name on console using print function.
#How many print statements did you write in your code?

"""- How many print statements did you write?"
- What if your name has 10 or 20 letters? Would it be practical to write so many print statements?"

**Solution:**
```
first_name = "pawan"
print(first_name[0])
print(first_name[1])
print(first_name[2])
print(first_name[3])
print(first_name[4])

#Number of print statements: 5
```

# 1. Loops
<a name="loops"></a>

Loops allow us to repeat a block of code for every item in a sequence, like the characters of your name.

Lets solve the above problem using loop:
"""

# Print all characters of the first name using the length
first_name = "Ali"

length_of_str = len(first_name)
i = 0 # Initialize the counter
while i < length_of_str: # Loop until i is less than the length of the name
    print(first_name[i]) # Access and print the character at index i
    i = i + 1  # Increment the counter

"""# 1.1. While Loops
<a name="loops"></a>

**Explanation**
1. Initialize the Counter:
```
i = 0
```
- Start with i = 0, which is the index of the first character.


2. Condition for the Loop
```
while i < length_of_name:
```
- Keep looping as long as i is less than the length of the string.

3. Access and Print Characters:
```
print(first_name[i])
```

- Use first_name[i] to get the character at index i and print it.

4. Increment the Counter:
```
i += 1
```
- Increase the value of i by 1 after each iteration to move to the next character.

###1. Debugging Exercises

Please explain what is wrong with the following code snippets. Along with fixing the code,
please provide an explanation using comment.

**Note:**
If the code is running for a long time, stop it by pressing the stop button
"""

# Print all characters of the first name using the length
first_name = input("Please enter your name: ")

length_of_str = len(first_name)
i = 0
while i < length_of_str:
    print(first_name[i])
    i+=1

# Print all characters of the first name using the length
first_name = input("Please enter your name: ")

length_of_str = len(first_name)
i = 0
while i < length_of_str:
    print(first_name[i])
    i = 1 + i

# Print all characters of the first name using the length
first_name = input("Please enter your name: ")
i=0
length_of_str = len(first_name)
while i < length_of_str:
    print(first_name[i])
    i = i + 1

"""###1. Coding Exercises

"""

#Prompt the user for a number between 5 and 10.
#Objective 1: Print all integers between 1 and user entered number (included).

#user_input: 5
#Expected output:'
# 1
# 2
# 3
# 4
# 5

number = int(input("Enter the number between 5 and 10. :"))
i = 1
if(number>=5 and number<=10):
    while(i<=number):
      print(i)
      i+=1
else:print("Enter number between 5 and 10.")

#Prompt the user for a number between 5 and 10.
#Objective 1:  Print all integers between 1 and user entered number (included) as comma separated values.

#user_input: 5
#Expected output:
# 1, 2, 3, 4 ,5

number = int(input("Enter the number between 5 and 10. :"))
i = 1
expected_output= ""
if(number>=5 and number<=10):
    while(i<=number):
      expected_output = expected_output + str(i)
      i+=1
else:print("Enter number between 5 and 10.")
print(",".join(expected_output))

#Prompt the user for a number between 5 and 10.
#Objective 1: Print all ODD integers between 1 and user entered number (included).
#Objective 2: Print the total integers printed

#user_input: 5
#Expected output:
# 1
# 3
# 5
# Total: 3

number = int(input("Enter the number between 5 and 10. :"))
i = 0
while(i<=number):
  if(i%2!=0):
    print(i)
  i+=1

#Prompt the user for a number between 5 and 10.
#Objective 1:Print all EVEN integers between 1 and user entered number (included) as comma separated values.
#Objective 2:Print the total integers printed

#user_input: 5
#Expected output:
# 2, 4
# Total: 2

number = int(input("Enter the number between 5 and 10. :"))
i = 1
expected_output1= ""
while(i<=number):
  if(i%2==0):
    expected_output1 = expected_output1 + str(i)
  i+=1
print(",".join(expected_output1))

#Prompt the user for a number between 5 and 10.
#Objective 1: If user has entered a number less than 5 or greater than 10,
#prompt the user to reenter the number

#Objective 2: Print all integers between 1
#and user entered number (included).

#user_input: 5
#Expected output:'
# 1
# 2
# 3
# 4
# 5

valid_input = False
while valid_input == False:
    # Prompt the user for a number between 5 and 10
    user_input = int(input("Enter a number between 5 and 10: "))

    # Check if the number is within the valid range
    if 5 <= user_input <= 10:
        valid_input = True  # Set the flag to True if the input is valid
    else:
        print("The number must be between 5 and 10. Please try again.")

# Print all integers between 1 and the user-entered number (inclusive)
i = 1
while i <= user_input:
    print(i)
    i += 1

number = int(input("Enter the number"))
minimum_num = 5
max_num = 10
i=1
MAX_ATTEMPT =3
ATTEMPT =1
while(ATTEMPT<MAX_ATTEMPT):
  if(minimum_num<=number and number<=max_num):
   while(i<=number):
      print(i)
      i+=1
      ATTEMPT=MAX_ATTEMPT
  else:
   print("The number must be between 5 and 10. Please try again.")
   number = int(input("Enter the number"))
   ATTEMPT+=1

user_input = int(input("Enter a number between 5 and 10: "))
if 5 <= user_input <= 10:
    valid_input = True
else:
    valid_input = False
    print("The number must be between 5 and 10. Please try again.")

max_attempts = 3
attempts = 0
while (valid_input == False and attempts < max_attempts):
    # Prompt the user for a number between 5 and 10
    user_input = int(input("Enter a number between 5 and 10: "))
    attempts = attempts + 1
    # Check if the number is within the valid range
    if 5 <= user_input <= 10:
        valid_input = True  # Set the flag to True if the input is valid
    else:
        print("The number must be between 5 and 10. Please try again.")

# Print all integers between 1 and the user-entered number (inclusive)
i = 1
if (attempts < max_attempts and valid_input == True):
    while i <= user_input:
        print(i)
        i += 1

